title: Dananji Shashiprabha
logo: /photo.jpeg
# description: dananjids@gmail.com
show_downloads: True
github:
  is_user_page: False
  is_project_page: False
  zip_url: LinkedIn: linkedin.com/in/dananji-shashiprabha-a454a1144
  tar_url: https://github.com/dananjids
  # repository_url: https://medium.com/@sarsenanayake
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
